services:
  db:
    container_name: postgress
    image: postgres
    environment:
      POSTGRES_USER: khalil
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  spring-boot-application:
    container_name: khalil-api
    image: kh4l1l1/spring-boot-application
    ports:
      - "8088:8080"
    networks:
      - db
    restart: unless-stopped
    command:
      - --spring.datasource.url=jdbc:postgresql://db:5432/customer

networks:
  db:
    driver: bridge

volumes:
  db: